### ISSUE TITLE
Consider including mac-minivnc in Mac OS image

### ISSUE THREAD

**Issue by jduerstock** [FozzTexx/globaltalk#2]
Hello!

Have you considered adding mac-minivnc ( https://github.com/marciot/mac-minivnc ) to your VM?  That might give you a little better remote control over it while it's running.

**Comment by FozzTexx** [comment]
There is no MacOS HD image as part of the repo, you can include that in your HD image if you feel it works better for you. My goal with my image is to keep it as stripped down as possible since it's intended to perform a single service, not normally used through the GUI at all. Avoiding use of the GUI was the main driving factor of the project, which is why I reverse engineered all the config and made it so that the settings can be passed in as command line arguments.
